### ISSUE TITLE
Various install.sh crashes due to unloaded kernel modules and missing dependencies on Bookworm Lite

### ISSUE THREAD

**Issue by Devonavar** [quaxalber/bluetooth_2_usb#116]
Just installed bluetooth_2_usb on a fresh image of Raspberry PI OS Lite (32-bit) (bookworm), using a Raspberry Pi Zero W.

I encountered three crashes during the install process due to missing dependencies.  These were easy to fix manually, but should probably be included in the script.  I'm filing it here as a bug because I don't know the code at all, so I feel safer reporting it and letting someone who knows the whole process better fix it.

Error #1:  (script error):  `Aborting installation. Failed installing dependencies.`
(python error):  
```
rpi_ws281x_wrap.c:154:11: fatal error: Python.h: No such file or directory
        154 | # include <Python.h>
```
Fix #1:  `sudo apt install python3-dev` (missing dependency)

Error #2:  (script error):  `Installation failed. The version information could not be retrieved.`
(python error):  `Exception: dwc2 module not present in your kernel. did you insmod it?`

Fix #2:  `sudo modprobe dwc2` (kernel module not loaded)

Error #3:  (script error):  `Installation failed. The version information could not be retrieved.`
(python error):  `Exception: libcomposite module not present in your kernel. did you insmod it?`

Fix #3:  `sudo modprobe libcomposite` (kernel module not loaded)

For both #2 and #3, the module was correctly added to /etc/modules, so presumably it would work on after reboot, and it just needs to be loaded in the script to the installation script doesn't error out.

Error #4:  `dtoverlay=dwc2` is written to the wrong file in a new Bookworm installation (which is now necessary due to the Python3.11 version requirement).  config.txt is now located at /boot/firmware/config.txt instead of /boot/config.txt

Workaround #4:  Manually add `dtoverlay=dwc2` to /boot/firmware/config.txt.  Presumably the script now needs some OS version checking code to fix this properly.

**Comment by mrjones-plip** [comment]
Just tested all these fixes on a Pi4 running Pi Lite 32-bit Bookworm  and can confirm all the above is correct. Thank you @Devonavar !!

Minor notes:

* `#1` - it is indeed super important to install `python3-dev`  - I researched the issue and came to the same conclusion.
* `#2` and `#3` -  indeed fixed by a reboot - but presumably the `modbprobe` in the install script would be a lot easier
* `#4` - I was struggling to debug this and couldn't understand the error, so really glad this ticket was opened!  Including the error message in case others are searching for it. I found it via `journalctl -u bluetooth_2_usb.service -n 50` :

```
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]: StopIteration
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]: 24-05-18 22:45:17 [ERROR] vc4-hdmi-1 HDMI Jack failed!
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]: Traceback (most recent call last):
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]:   File "/home/pi/bluetooth_2_usb/src/bluetooth_2_usb/relay.py", line 248, in _async_relay_events
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]:     relay = DeviceRelay(device, self._grab_devices)
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]:   File "/home/pi/bluetooth_2_usb/src/bluetooth_2_usb/relay.py", line 120, in __init__
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]:     init_usb_gadgets()
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]:   File "/home/pi/bluetooth_2_usb/src/bluetooth_2_usb/relay.py", line 46, in init_usb_gadgets
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]:     usb_hid.enable(
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]:   File "/home/pi/bluetooth_2_usb/venv/lib/python3.11/site-packages/usb_hid.py", line 758, in enable
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]:     udc = next(Path("/sys/class/udc/").glob("*"))
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]: StopIteration
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]: 24-05-18 22:45:17 [ERROR] VB87MT Keyboard failed!
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]: Traceback (most recent call last):
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]:   File "/home/pi/bluetooth_2_usb/src/bluetooth_2_usb/relay.py", line 248, in _async_relay_events
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]:     relay = DeviceRelay(device, self._grab_devices)
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]:   File "/home/pi/bluetooth_2_usb/src/bluetooth_2_usb/relay.py", line 120, in __init__
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]:     init_usb_gadgets()
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]:   File "/home/pi/bluetooth_2_usb/src/bluetooth_2_usb/relay.py", line 46, in init_usb_gadgets
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]:     usb_hid.enable(
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]:   File "/home/pi/bluetooth_2_usb/venv/lib/python3.11/site-packages/usb_hid.py", line 758, in enable
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]:     udc = next(Path("/sys/class/udc/").glob("*"))
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 18 22:45:17 raspberrypi bluetooth_2_usb[775]: StopIteration
```

**Comment by Devonavar** [comment]
Thanks!

**Comment by Devonavar** [comment]
Reopening since I see you were using my workarounds and haven't committed anything yet.  I'll let the process work as intended...

**Comment by quaxalber** [comment]
Hey there, 

Thanks a lot for your input. 

`python3-dev` is now added to the installer.

**Comment by mrjones-plip** [comment]
Great - thank you!

**Comment by PhilippParis** [comment]
Hi!
i just got the setup working with the Pi Zero 2 W!
additionally to the problems described in this issue I had the problem when adding "dtoverlay=dwc2" to config.txt:

the default config.txt looks like this

```
# For more options and information see
# http://rptl.io/configtxt
# Some settings may impact device functionality. See link above for details

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

# Additional overlays and parameters are documented
# /boot/firmware/overlays/README

# Automatically load overlays for detected cameras
camera_auto_detect=1

# Automatically load overlays for detected DSI displays
display_auto_detect=1

# Automatically load initramfs files, if found
auto_initramfs=1

# Enable DRM VC4 V3D driver
dtoverlay=vc4-kms-v3d
max_framebuffers=2

# Don't have the firmware create an initial video= setting in cmdline.txt.
# Use the kernel's default instead.
disable_fw_kms_setup=1

# Run in 64-bit mode
arm_64bit=1

# Disable compensation for displays with overscan
disable_overscan=1

# Run as fast as firmware / board allows
arm_boost=1

[cm4]
# Enable host mode on the 2711 built-in XHCI USB controller.
# This line should be removed if the legacy DWC2 controller is required
# (e.g. for USB device mode) or if USB support is not required.
otg_mode=1

[cm5]
dtoverlay=dwc2,dr_mode=host

[all]
```

the script does not add dtoverlay=dwc2 to the file because it already exists.
but there are the follwing problems:
- it is under the [cm5] section, which is ignored for pi zero
- and dr_mode=host is (probably) wrong (i have not tested it, i just assume)

i update the config.txt to the following and now it works!
```
# For more options and information see
# http://rptl.io/configtxt
# Some settings may impact device functionality. See link above for details

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

# Additional overlays and parameters are documented
# /boot/firmware/overlays/README

# Automatically load overlays for detected cameras
camera_auto_detect=1

# Automatically load overlays for detected DSI displays
display_auto_detect=1

# Automatically load initramfs files, if found
auto_initramfs=1

# Enable DRM VC4 V3D driver
dtoverlay=vc4-kms-v3d
max_framebuffers=2

# Don't have the firmware create an initial video= setting in cmdline.txt.
# Use the kernel's default instead.
disable_fw_kms_setup=1

# Run in 64-bit mode
arm_64bit=1

# Disable compensation for displays with overscan
disable_overscan=1

# Run as fast as firmware / board allows
arm_boost=1

[cm4]
# Enable host mode on the 2711 built-in XHCI USB controller.
# This line should be removed if the legacy DWC2 controller is required
# (e.g. for USB device mode) or if USB support is not required.
otg_mode=1

[all]
dtoverlay=dwc2,dr_mode=peripheral

[all]
```

maybe you can update install.sh to fix that

thx!

**Comment by quaxalber** [comment]
Hi there, 

Thanks so much for all your feedback. And apologies for the delayed response. 

Please check out the linked PR, which should hopefully fix the spotted issues, e.g.;

```console
cd ~/bluetooth_2_usb && git checkout fix/install
```

I have tested to set up a RPi Zero W from scratch using RPi Imager and the default RPi OS (Bookworm, 2024-11-19). 
Please let me know how that works for you guys! 

Cheers

**Comment by quaxalber** [comment]
Merged the PRs into main in v0.8.2

You may update by running:

```console
cd ~/bluetooth_2_usb && git checkout main && git pull && sudo scripts/update.sh

```

Please let me know how that works for you. 

Thanks
